server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xiaobaicai789/spring-cloud-learning
          #username: git账号
          #password: git密码
          search-paths: config
          default-label: master
